### ISSUE TITLE
0.6.2 Not working on Atom v0.134.0

### ISSUE THREAD

**Issue by jsanta** [postcasio/custom-title#2]
Failed to activate package named 'custom-title' TypeError: undefined is not a function
  at /home/jsanta/.atom/packages/custom-title/lib/custom-title.coffee:36:19

Line 36: atom.workspace.updateWindowTitle()

If you need me to provide other information please tell.
